### ISSUE TITLE
feat: tibiadata-api-go image should support digest too

### ISSUE THREAD

**Issue by tobiasehlert** [TibiaData/tibiadata-helm-charts#12]
Today we only support specification of `tag` but we'd want to use `digest` sha256 instead.

The chart is like this today:
```yaml
image:
  repository: ghcr.io/tibiadata/tibiadata-api-go
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
```

This would enable ArgoCD in an app-of-apps setup to deploy helm-chart by digest instead of the _edge_ image for instance.

Maybe something similar to this:
https://blog.andyserver.com/2021/09/adding-image-digest-references-to-your-helm-charts/
